package com.neuedu.dao;

import com.neuedu.pojo.Category;
import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    /**
     * 更新商品的部分信息
     * @param product
     * @return
     */
    int updateByPrimaryKeySelective(Product product);

    /**
     * 后台-搜索商品
     * @param productId
     * @param productName
     * @return
     */
    List<Product> searchProduct(@Param("productId") Integer productId,
                                @Param("productName") String productName);

    /**
     * 前台-搜索商品
     * @param categorySet
     * @param categoryId
     * @return
     */
    List<Product> findProductByCategoryIdsAndKeywords(@Param("categorySet") Set<Category> categorySet,
                                                      @Param("keyword") String keyword);
}